### ISSUE TITLE
pull requests directly to master

### ISSUE THREAD

**Issue by lheagy** [simpeg/simpeg#651]
To speed up getting features live into SimPEG, we could do pull requests directly onto master. 

## Impacts
- your features are rapidly live to the world!
- pull requests should be small and focussed
- pull request notes will be used as the release notes and so should contain sufficient detail to describe the changes, any breaks in backwards compatibility, etc.  

## TODO's
- [x] switch main branch to master on github
- [x] ensure dev and master synced
- [x] change base of current pr's onto dev to master
- [x] delete dev branch
- [ ] delete http://dev-docs.simpeg.xyz
- [x] update travis to remove deployment sequence from dev 

## Timeline
We can do this as soon as #628 is in. Are there any concerns about doing this now? cc @rowanc1, @grosenkj, @sgkang, @thast, @fourndo. Can you please give a 👍 or 👎?

**Comment by fourndo** [comment]
👍 Make it better, faster, stronger: https://youtu.be/gAjR4_CbPpQ

**Comment by rowanc1** [comment]
👍 Yep, I think this will bring features into master faster as well!

**Comment by lheagy** [comment]
Wonderful! I will get started on this :)

**Comment by lheagy** [comment]
- [ ] @rowanc1: can you remove the dev-docs subdomain from simpeg.xyz on godaddy? Thanks!

**Comment by rowanc1** [comment]
![image](https://user-images.githubusercontent.com/913249/32907549-9a096698-cabd-11e7-8404-b48e422cbdd5.png)

**Comment by rowanc1** [comment]
I have deleted the cname record.
